### ISSUE TITLE
2.0.2 is not compatible with Android X

### ISSUE THREAD

**Issue by dpgc11** [ittianyu/BottomNavigationViewEx#150]
In issue #103 , it's mentioned that it has been migrated to Android X. However, the latest version doesn't reflect the changes. It crashes the app as mentioned in issue #101 . I have added Jetifier and AndroidX to my gradle.properties file

**Comment by dpgc11** [comment]
I have fixed it. You need to modify your proguard-rules.pro file with the following:

`-keep public class com.google.android.material.bottomnavigation.BottomNavigationView { *; }`
`-keep public class com.google.android.material.bottomnavigation.BottomNavigationMenuView { *; }`
`-keep public class com.google.android.material.bottomnavigation.BottomNavigationPresenter { *; }`
`-keep public class com.google.android.material.bottomnavigation.BottomNavigationItemView { *; }`

**Comment by ittianyu** [comment]
Thanks. I have update the doc.

**Comment by yalematta** [comment]
The problem persists even after updating the  proguard-rules.pro file.
